/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as ProductsGlp1WeightLossRouteImport } from './routes/products/glp-1-weight-loss'
import { Route as CategorySlugRouteImport } from './routes/category/$slug'
import { Route as ApiWebhooksPrescribeRxRouteImport } from './routes/api/webhooks/prescribe-rx'
import { Route as ApiPrxProductsRouteImport } from './routes/api/prx/products'
import { Route as ApiPrxPatientsRouteImport } from './routes/api/prx/patients'
import { Route as ApiPrxOrdersRouteImport } from './routes/api/prx/orders'
import { Route as ApiPrxMeRouteImport } from './routes/api/prx/me'
import { Route as ApiPrxIntakeRouteImport } from './routes/api/prx/intake'
import { Route as ApiPrxHealthRouteImport } from './routes/api/prx/health'
import { Route as ApiPrxCheckoutRouteImport } from './routes/api/prx/checkout'
import { Route as ApiPrxCatalogRouteImport } from './routes/api/prx/catalog'
import { Route as ApiPrxOrdersOrderIdRouteImport } from './routes/api/prx/orders.$orderId'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsGlp1WeightLossRoute = ProductsGlp1WeightLossRouteImport.update({
  id: '/products/glp-1-weight-loss',
  path: '/products/glp-1-weight-loss',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPrescribeRxRoute = ApiWebhooksPrescribeRxRouteImport.update({
  id: '/api/webhooks/prescribe-rx',
  path: '/api/webhooks/prescribe-rx',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrxProductsRoute = ApiPrxProductsRouteImport.update({
  id: '/api/prx/products',
  path: '/api/prx/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrxPatientsRoute = ApiPrxPatientsRouteImport.update({
  id: '/api/prx/patients',
  path: '/api/prx/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrxOrdersRoute = ApiPrxOrdersRouteImport.update({
  id: '/api/prx/orders',
  path: '/api/prx/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrxMeRoute = ApiPrxMeRouteImport.update({
  id: '/api/prx/me',
  path: '/api/prx/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrxIntakeRoute = ApiPrxIntakeRouteImport.update({
  id: '/api/prx/intake',
  path: '/api/prx/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrxHealthRoute = ApiPrxHealthRouteImport.update({
  id: '/api/prx/health',
  path: '/api/prx/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrxCheckoutRoute = ApiPrxCheckoutRouteImport.update({
  id: '/api/prx/checkout',
  path: '/api/prx/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrxCatalogRoute = ApiPrxCatalogRouteImport.update({
  id: '/api/prx/catalog',
  path: '/api/prx/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrxOrdersOrderIdRoute = ApiPrxOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => ApiPrxOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/confirmation': typeof ConfirmationRoute
  '/quiz': typeof QuizRoute
  '/category/$slug': typeof CategorySlugRoute
  '/products/glp-1-weight-loss': typeof ProductsGlp1WeightLossRoute
  '/account/': typeof AccountIndexRoute
  '/api/prx/catalog': typeof ApiPrxCatalogRoute
  '/api/prx/checkout': typeof ApiPrxCheckoutRoute
  '/api/prx/health': typeof ApiPrxHealthRoute
  '/api/prx/intake': typeof ApiPrxIntakeRoute
  '/api/prx/me': typeof ApiPrxMeRoute
  '/api/prx/orders': typeof ApiPrxOrdersRouteWithChildren
  '/api/prx/patients': typeof ApiPrxPatientsRoute
  '/api/prx/products': typeof ApiPrxProductsRoute
  '/api/webhooks/prescribe-rx': typeof ApiWebhooksPrescribeRxRoute
  '/api/prx/orders/$orderId': typeof ApiPrxOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/confirmation': typeof ConfirmationRoute
  '/quiz': typeof QuizRoute
  '/category/$slug': typeof CategorySlugRoute
  '/products/glp-1-weight-loss': typeof ProductsGlp1WeightLossRoute
  '/account': typeof AccountIndexRoute
  '/api/prx/catalog': typeof ApiPrxCatalogRoute
  '/api/prx/checkout': typeof ApiPrxCheckoutRoute
  '/api/prx/health': typeof ApiPrxHealthRoute
  '/api/prx/intake': typeof ApiPrxIntakeRoute
  '/api/prx/me': typeof ApiPrxMeRoute
  '/api/prx/orders': typeof ApiPrxOrdersRouteWithChildren
  '/api/prx/patients': typeof ApiPrxPatientsRoute
  '/api/prx/products': typeof ApiPrxProductsRoute
  '/api/webhooks/prescribe-rx': typeof ApiWebhooksPrescribeRxRoute
  '/api/prx/orders/$orderId': typeof ApiPrxOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/confirmation': typeof ConfirmationRoute
  '/quiz': typeof QuizRoute
  '/category/$slug': typeof CategorySlugRoute
  '/products/glp-1-weight-loss': typeof ProductsGlp1WeightLossRoute
  '/account/': typeof AccountIndexRoute
  '/api/prx/catalog': typeof ApiPrxCatalogRoute
  '/api/prx/checkout': typeof ApiPrxCheckoutRoute
  '/api/prx/health': typeof ApiPrxHealthRoute
  '/api/prx/intake': typeof ApiPrxIntakeRoute
  '/api/prx/me': typeof ApiPrxMeRoute
  '/api/prx/orders': typeof ApiPrxOrdersRouteWithChildren
  '/api/prx/patients': typeof ApiPrxPatientsRoute
  '/api/prx/products': typeof ApiPrxProductsRoute
  '/api/webhooks/prescribe-rx': typeof ApiWebhooksPrescribeRxRoute
  '/api/prx/orders/$orderId': typeof ApiPrxOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkout'
    | '/confirmation'
    | '/quiz'
    | '/category/$slug'
    | '/products/glp-1-weight-loss'
    | '/account/'
    | '/api/prx/catalog'
    | '/api/prx/checkout'
    | '/api/prx/health'
    | '/api/prx/intake'
    | '/api/prx/me'
    | '/api/prx/orders'
    | '/api/prx/patients'
    | '/api/prx/products'
    | '/api/webhooks/prescribe-rx'
    | '/api/prx/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout'
    | '/confirmation'
    | '/quiz'
    | '/category/$slug'
    | '/products/glp-1-weight-loss'
    | '/account'
    | '/api/prx/catalog'
    | '/api/prx/checkout'
    | '/api/prx/health'
    | '/api/prx/intake'
    | '/api/prx/me'
    | '/api/prx/orders'
    | '/api/prx/patients'
    | '/api/prx/products'
    | '/api/webhooks/prescribe-rx'
    | '/api/prx/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/checkout'
    | '/confirmation'
    | '/quiz'
    | '/category/$slug'
    | '/products/glp-1-weight-loss'
    | '/account/'
    | '/api/prx/catalog'
    | '/api/prx/checkout'
    | '/api/prx/health'
    | '/api/prx/intake'
    | '/api/prx/me'
    | '/api/prx/orders'
    | '/api/prx/patients'
    | '/api/prx/products'
    | '/api/webhooks/prescribe-rx'
    | '/api/prx/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  ConfirmationRoute: typeof ConfirmationRoute
  QuizRoute: typeof QuizRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductsGlp1WeightLossRoute: typeof ProductsGlp1WeightLossRoute
  AccountIndexRoute: typeof AccountIndexRoute
  ApiPrxCatalogRoute: typeof ApiPrxCatalogRoute
  ApiPrxCheckoutRoute: typeof ApiPrxCheckoutRoute
  ApiPrxHealthRoute: typeof ApiPrxHealthRoute
  ApiPrxIntakeRoute: typeof ApiPrxIntakeRoute
  ApiPrxMeRoute: typeof ApiPrxMeRoute
  ApiPrxOrdersRoute: typeof ApiPrxOrdersRouteWithChildren
  ApiPrxPatientsRoute: typeof ApiPrxPatientsRoute
  ApiPrxProductsRoute: typeof ApiPrxProductsRoute
  ApiWebhooksPrescribeRxRoute: typeof ApiWebhooksPrescribeRxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/glp-1-weight-loss': {
      id: '/products/glp-1-weight-loss'
      path: '/products/glp-1-weight-loss'
      fullPath: '/products/glp-1-weight-loss'
      preLoaderRoute: typeof ProductsGlp1WeightLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/prescribe-rx': {
      id: '/api/webhooks/prescribe-rx'
      path: '/api/webhooks/prescribe-rx'
      fullPath: '/api/webhooks/prescribe-rx'
      preLoaderRoute: typeof ApiWebhooksPrescribeRxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prx/products': {
      id: '/api/prx/products'
      path: '/api/prx/products'
      fullPath: '/api/prx/products'
      preLoaderRoute: typeof ApiPrxProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prx/patients': {
      id: '/api/prx/patients'
      path: '/api/prx/patients'
      fullPath: '/api/prx/patients'
      preLoaderRoute: typeof ApiPrxPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prx/orders': {
      id: '/api/prx/orders'
      path: '/api/prx/orders'
      fullPath: '/api/prx/orders'
      preLoaderRoute: typeof ApiPrxOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prx/me': {
      id: '/api/prx/me'
      path: '/api/prx/me'
      fullPath: '/api/prx/me'
      preLoaderRoute: typeof ApiPrxMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prx/intake': {
      id: '/api/prx/intake'
      path: '/api/prx/intake'
      fullPath: '/api/prx/intake'
      preLoaderRoute: typeof ApiPrxIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prx/health': {
      id: '/api/prx/health'
      path: '/api/prx/health'
      fullPath: '/api/prx/health'
      preLoaderRoute: typeof ApiPrxHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prx/checkout': {
      id: '/api/prx/checkout'
      path: '/api/prx/checkout'
      fullPath: '/api/prx/checkout'
      preLoaderRoute: typeof ApiPrxCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prx/catalog': {
      id: '/api/prx/catalog'
      path: '/api/prx/catalog'
      fullPath: '/api/prx/catalog'
      preLoaderRoute: typeof ApiPrxCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prx/orders/$orderId': {
      id: '/api/prx/orders/$orderId'
      path: '/$orderId'
      fullPath: '/api/prx/orders/$orderId'
      preLoaderRoute: typeof ApiPrxOrdersOrderIdRouteImport
      parentRoute: typeof ApiPrxOrdersRoute
    }
  }
}

interface ApiPrxOrdersRouteChildren {
  ApiPrxOrdersOrderIdRoute: typeof ApiPrxOrdersOrderIdRoute
}

const ApiPrxOrdersRouteChildren: ApiPrxOrdersRouteChildren = {
  ApiPrxOrdersOrderIdRoute: ApiPrxOrdersOrderIdRoute,
}

const ApiPrxOrdersRouteWithChildren = ApiPrxOrdersRoute._addFileChildren(
  ApiPrxOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  ConfirmationRoute: ConfirmationRoute,
  QuizRoute: QuizRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductsGlp1WeightLossRoute: ProductsGlp1WeightLossRoute,
  AccountIndexRoute: AccountIndexRoute,
  ApiPrxCatalogRoute: ApiPrxCatalogRoute,
  ApiPrxCheckoutRoute: ApiPrxCheckoutRoute,
  ApiPrxHealthRoute: ApiPrxHealthRoute,
  ApiPrxIntakeRoute: ApiPrxIntakeRoute,
  ApiPrxMeRoute: ApiPrxMeRoute,
  ApiPrxOrdersRoute: ApiPrxOrdersRouteWithChildren,
  ApiPrxPatientsRoute: ApiPrxPatientsRoute,
  ApiPrxProductsRoute: ApiPrxProductsRoute,
  ApiWebhooksPrescribeRxRoute: ApiWebhooksPrescribeRxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
